# Generated by Django 5.2.14 on 2026-09-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querylog',
            name='model_used',
            field=models.CharField(default='google/gemini-3.1-flash-lite', max_length=100),
        ),
    ]
